import { Geist, Geist_Mono, Inconsolata, Roboto_Slab } from "next/font/google";
import "./globals.css";

const inconsolata = Inconsolata({
  variable: "--font-inconsolata",
  subsets: ["latin"],
  weight: ["400", "500", "700", "800"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const isDev = process.env.NODE_ENV === "development";

  return (
    <html lang="en">
      <body
        className={`${inconsolata.variable} ${isDev && "debug-screens"} font-sans antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
